configs= [
#--------------------
# Standard options:

# " --prefix=PREFIX",

# Licensing options:
" --disable-gpl",
# " --enable-version3",
" --disable-nonfree",

# Configuration options:
# " --disable-static",
# " --enable-shared",
# " --enable-small",
" --enable-runtime-cpudetect",
" --disable-gray",
" --disable-swscale-alpha",

# Program options:
" --disable-programs",
" --disable-ffmpeg",
" --disable-ffplay",
" --disable-ffprobe",
#" --disable-ffserver",

# Documentation options:
" --disable-doc",
" --disable-htmlpages",
" --disable-manpages",
" --disable-podpages",
" --disable-txtpages",

# Component options:
" --disable-avdevice",
" --enable-avcodec",
" --enable-avformat",
" --enable-avutil",
" --enable-swresample",
" --enable-swscale",
" --disable-postproc",
" --enable-avfilter",
" --disable-avresample",
# " --disable-pthreads",
# " --disable-w32threads",
# " --disable-os2threads",
" --enable-network",
# " --disable-dct",
# " --disable-dwt",
# " --disable-lsp",
# " --disable-lzo",
# " --disable-mdct",
# " --disable-rdft",
# " --disable-fft",

# Hardware accelerators:
" --disable-d3d11va",
" --disable-dxva2",
" --disable-vaapi",
#" --disable-vda",
" --disable-vdpau",
" --disable-videotoolbox",

# Individual component options:
# " --disable-everything",
" --disable-encoders",
" --enable-encoder=png",

# ./configure --list-decoders
" --disable-decoders",
" --enable-decoder=aac",
" --enable-decoder=aac_latm",
" --enable-decoder=flv",
" --enable-decoder=h264",
" --enable-decoder=mp3*",
" --enable-decoder=vp6f",
" --enable-decoder=flac",
" --enable-decoder=hevc",
" --enable-decoder=vp8",
" --enable-decoder=vp9",
" --enable-demuxer=ijk*",

" --disable-hwaccels",

# ./configure --list-muxers
" --disable-muxers",
" --enable-muxer=mp4",

# ./configure --list-demuxers
" --disable-demuxers",
" --enable-demuxer=aac",
" --enable-demuxer=concat",
" --enable-demuxer=data",
" --enable-demuxer=flv",
" --enable-demuxer=hls",
" --enable-demuxer=live_flv",
" --enable-demuxer=mov",
" --enable-demuxer=mp3",
" --enable-demuxer=mpegps",
" --enable-demuxer=mpegts",
" --enable-demuxer=mpegvideo",
" --enable-demuxer=flac",
" --enable-demuxer=hevc",
" --enable-demuxer=webm_dash_manifest",

# ./configure --list-parsers
" --disable-parsers",
" --enable-parser=aac",
" --enable-parser=aac_latm",
" --enable-parser=h264",
" --enable-parser=flac",
" --enable-parser=hevc",

# ./configure --list-bsf
" --enable-bsfs",
" --disable-bsf=chomp",
" --disable-bsf=dca_core",
" --disable-bsf=dump_extradata",
" --disable-bsf=hevc_mp4toannexb",
" --disable-bsf=imx_dump_header",
" --disable-bsf=mjpeg2jpeg",
" --disable-bsf=mjpega_dump_header",
" --disable-bsf=mov2textsub",
" --disable-bsf=mp3_header_decompress",
" --disable-bsf=mpeg4_unpack_bframes",
" --disable-bsf=noise",
" --disable-bsf=remove_extradata",
" --disable-bsf=text2movsub",
" --disable-bsf=vp9_superframe",
" --disable-bsf=eac3_core",

# ./configure --list-protocols
" --enable-protocols",
" --enable-protocol=async",
" --disable-protocol=bluray",
" --disable-protocol=concat",
" --disable-protocol=crypto",
" --disable-protocol=ffrtmpcrypt",
" --enable-protocol=ffrtmphttp",
" --disable-protocol=gopher",
" --disable-protocol=icecast",
" --disable-protocol=librtmp*",
" --disable-protocol=libssh",
" --disable-protocol=md5",
" --disable-protocol=mmsh",
" --disable-protocol=mmst",
" --disable-protocol=rtmp*",
" --enable-protocol=rtmp",
" --enable-protocol=rtmpt",
" --disable-protocol=rtp",
" --disable-protocol=sctp",
" --disable-protocol=srtp",
" --disable-protocol=subfile",
" --disable-protocol=unix",

#
" --disable-devices",
" --disable-filters",

# External library support:
" --disable-iconv",
" --disable-audiotoolbox",
" --disable-videotoolbox",

# ...

# Advanced options (experts only):
# " --cross-prefix=${FF_CROSS_PREFIX}-",
# " --enable-cross-compile",
# " --sysroot=PATH",
# " --sysinclude=PATH",
# " --target-os=TAGET_OS",
# " --target-exec=CMD",
# " --target-path=DIR",
# " --toolchain=NAME",
# " --nm=NM",
# " --ar=AR",
# " --as=AS",
# " --yasmexe=EXE",
# " --cc=CC",
# " --cxx=CXX",
# " --dep-cc=DEPCC",
# " --ld=LD",
# " --host-cc=HOSTCC",
# " --host-cflags=HCFLAGS",
# " --host-cppflags=HCPPFLAGS",
# " --host-ld=HOSTLD",
# " --host-ldflags=HLDFLAGS",
# " --host-libs=HLIBS",
# " --host-os=OS",
# " --extra-cflags=ECFLAGS",
# " --extra-cxxflags=ECFLAGS",
# " --extra-ldflags=ELDFLAGS",
# " --extra-libs=ELIBS",
# " --extra-version=STRING",
# " --optflags=OPTFLAGS",
# " --build-suffix=SUFFIX",
# " --malloc-prefix=PREFIX",
# " --progs-suffix=SUFFIX",
# " --arch=ARCH",
# " --cpu=CPU",
# " --enable-pic",
# " --enable-sram",
# " --enable-thumb",
# " --disable-symver",
# " --enable-hardcoded-tables",
# " --disable-safe-bitstream-reader",
# " --enable-memalign-hack",
# " --enable-lto",

# Optimization options (experts only):
# " --enable-asm",
# " --disable-altivec",
# " --disable-amd3dnow",
# " --disable-amd3dnowext",
# " --disable-mmx",
# " --disable-mmxext",
# " --disable-sse",
# " --disable-sse2",
# " --disable-sse3",
# " --disable-ssse3",
# " --disable-sse4",
# " --disable-sse42",
# " --disable-avx",
# " --disable-fma4",
# " --disable-armv5te",
# " --disable-armv6",
# " --disable-armv6t2",
# " --disable-vfp",
# " --disable-neon",
# " --disable-vis",
# " --enable-inline-asm",
# " --disable-yasm",
# " --disable-mips32r2",
# " --disable-mipsdspr1",
# " --disable-mipsdspr2",
# " --disable-mipsfpu",
# " --disable-fast-unaligned",

# Developer options (useful when working on FFmpeg itself):
# " --enable-coverage",
# " --disable-debug",
# " --enable-debug=LEVEL",
# " --disable-optimizations",
# " --enable-extra-warnings",
# " --disable-stripping",
# " --assert-level=level",
# " --enable-memory-poisoning",
# " --valgrind=VALGRIND",
# " --enable-ftrapv",
# " --samples=PATH",
# " --enable-xmm-clobber-test",
# " --enable-random",
# " --disable-random",
# " --enable-random=LIST",
# " --disable-random=LIST",
# " --random-seed=VALUE",
" --disable-linux-perf",
" --disable-bzlib",
]
